Attention model evaluation PIDML adjustments
mytkom/O2Physics pull request #2
Opened 2024-07-23 08:14 UTC by mytkom

2024-07-23 12:31 UTC, WildJellybear approved these changes
:D

2024-07-23 12:31 UTC, WildJellybear commented on Tools/PIDML/pidMLEffAndPurProducer.cxx
> +    if (track.pt() <= cfgTofPtCut || (track.tofSignal() - kTOFMissingSignal) < kEpsilon) {
dito

2024-07-23 12:31 UTC, WildJellybear commented on Tools/PIDML/pidMLBatchEffAndPurProducer.cxx
> +    if (track.pt() < nSigmaTofPtCut || (track.tofSignal() - tofMissing) < eps) {
add abs to tofSignal check

2024-07-23 12:31 UTC, WildJellybear commented on Tools/PIDML/pidMLEffAndPurProducer.cxx
> +    if (track.pt() <= cfgTofPtCut || (track.tofSignal() - kTOFMissingSignal) < kEpsilon) {
(not important) keep one convention - in batch there is exclusive pt cut, just to be sure both scripts would give same results

2024-07-23 12:31 UTC, WildJellybear commented on Tools/PIDML/pidOnnxModel.h
> +    if ((track.tofSignal() - kTOFMissingSignal) > kEpsilon) {
dito

2024-07-23 12:31 UTC, WildJellybear commented on Tools/PIDML/pidMLBatchEffAndPurProducer.cxx
> +/// \author Michał Olędzki <mioledzk@cern.ch>
my email is m.oledzki XD

2024-07-30 06:20 UTC, saganatt commented on Tools/PIDML/pidOnnxModel.h
> +    inputValues.insert(inputValues.end(), {track.p(), track.pt(), track.px(), track.py(), track.pz(), static_cast<float>(track.sign()), scaledX, scaledY, scaledZ, scaledAlpha, static_cast<float>(trac
Czy w takiej samej kolejności model miał dane przy trenowaniu?

2024-07-30 06:24 UTC, saganatt requested changes

2024-07-30 06:24 UTC, saganatt commented on Tools/PIDML/pidOnnxModel.h
> -  float sigmoid(float x)
Może sigmoida na razie nie będziemy usuwać

2024-07-30 06:24 UTC, saganatt commented
Poza tymi 2 uwagami dla mnie spoko.
I tak bym poczekała z mergem, aż na pewno model podziała na Run 3.

2024-07-30 07:42 UTC, mytkom commented on Tools/PIDML/pidOnnxModel.h
> +    inputValues.insert(inputValues.end(), {track.p(), track.pt(), track.px(), track.py(), track.pz(), static_cast<float>(track.sign()), scaledX, scaledY, scaledZ, scaledAlpha, static_cast<float>(trac
Tak, generujemy columns_for_training.json podczas trenowania:
```json
{
    "columns_for_training": [
        "fTPCSignal",
        "fTRDSignal",
        "fTRDPattern",
        "fTOFSignal",
        "fBeta",
        "fP",
        "fPt",
        "fPx",
        "fPy",
        "fPz",
        "fSign",
        "fX",
        "fY",
        "fZ",
        "fAlpha",
        "fTrackType",
        "fTPCNClsShared",
        "fDcaXY",
        "fDcaZ"
    ]
}
```
Kolejność jest na jego podstawie.

2024-08-02 17:08 UTC, saganatt approved these changes

2024-08-02 17:09 UTC, saganatt commented
For some reason clang format wants additional indentation. Please check you have all brackets etc. set right.

To be merged after successful tests

2024-08-05 11:14 UTC, mytkom commented
I will close this PR and make 3 separate just so I skip conflicts resolving and everything would be cleaner (it means 3 PRs to original O2Physics repo from this fork, but each one would be logically separated)

2024-08-05 11:14 UTC, mytkom commented
That's it.

2024-08-05 11:14 UTC, closed without merging